### ISSUE TITLE
android 11上支付宝调不起来(已解决）

### ISSUE THREAD

**Issue by New-Zero-Zero** [Cuieney/RxPay#21]
回调出现一个 4000 的错误

**Comment by New-Zero-Zero** [comment]
``021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx W/System.err:     at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at android.os.Parcel.createException(Parcel.java:2360)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at android.os.Parcel.readException(Parcel.java:2343)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at android.os.Parcel.readException(Parcel.java:2285)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceIdWithFeature(ITelephony.java:11481)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1939)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.util.a.<init>(SourceFile:38)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.util.a.a(SourceFile:27)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.tid.b.a(SourceFile:79)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.app.statistic.c.<init>(SourceFile:1229)
2021-11-19 11:41:42.826 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.app.statistic.a.a(SourceFile:21)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.alipay.sdk.app.PayTask.<init>(SourceFile:58)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at com.cuieney.sdk.rxpay.alipay.AlipayWay$payMoney$1.subscribe(AlipayWay.kt:29)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:12995)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:12995)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:12941)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-19 11:41:42.827 15316-15809/com.xxxxx.xxxxx  W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-11-19 11:41:42.854 15316-15316/com.xxxxx.xxxxx  D/DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true

RxCachedThreadS: type=1400 audit(0.0:6094260): avc: denied { read } for name="version" dev="proc" ino=4026532262 scontext=u:r:untrusted_app:s0:c188,c258,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.shangcheng.ajin
2021-11-19 11:41:42.919 15316-15809/com.xxxxx.xxxxx E/Rxpay: 4000,

**Comment by New-Zero-Zero** [comment]
在清单文件中 queries 段落中加入以下代码(< />符号我去掉了 自己添加）
15.8.02
更新日期：2021-03-11
Android SDK
• 若您的应用已经提升 targetSdkVersion 到 30 或以上，请在 AndroidManifest.xml 中加入以下内容，并更新 Gradle 插件版本，以符合 Android应用可见性机制 的要求：
文档地址 https://opendocs.alipay.com/open/54/104509
 正式环境 
package android:name="com.eg.android.AlipayGphone" 
沙箱环境 
package android:name="com.eg.android.AlipayGphoneRC" 
package android:name="hk.alipay.wallet"
